// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

module.exports = {
  mainSidebar: [
    {
      type: "category",
      label: "Overview",
      className: "menu_outer_list",
      collapsible: false,
      items: ["readme"],
    },
    {
      type: "category",
      label: "dApps",
      className: "menu_outer_list",
      collapsible: false,
      items: [
        "dApps/getting-started",
        {
          type: "category",
          label: "Web3Modal",
          collapsible: true,
          items: [
            "dApps/web3modal/installation",
          ],
        },
        {
          type: "category",
          label: "SDKs",
          collapsible: true,
          items: [
            "dApps/sdks/installation",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Wallets",
      className: "menu_outer_list",
      collapsible: false,
      items: ["advanced/relay-server"],
    },
    {
      type: "category",
      label: "Advanced",
      collapsible: false,
      className: "menu_outer_list",
      items: [
        "advanced/migrating-from-v1.0",
        "advanced/relay-server",
        {
          type: "category",
          label: "RPC Reference",
          items: [
            "advanced/rpc-reference/ethereum-rpc",
            "advanced/rpc-reference/cosmos-rpc",
            "advanced/rpc-reference/solana-rpc",
            "advanced/rpc-reference/stellar-rpc",
          ],
        },
      ],
    },
  ],
  specs: [
    {
      type: "autogenerated",
      dirName: "specs",
    },
  ],
};
